const January = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
  31: { title: "" },
};
const February = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
};
const March = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
  31: { title: "" },
};
const April = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
};
const May = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
  31: { title: "" },
};
const June = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
};
const July = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
  31: { title: "" },
};
const August = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
  31: { title: "" },
};
const September = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
};
const October = {
  1: { title: "" },
  2: { title: "" },
  3: { title: "" },
  4: { title: "" },
  5: { title: "" },
  6: { title: "" },
  7: { title: "" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: {
    title: "Luke 16:1-18:30",
  },
  14: {
    title: "Luke 18:31-21:38",
  },
  15: {
    title: "Luke 22-24",
  },
  16: {
    title: "John 1-4",
  },
  17: {
    title: "John 5-7",
  },
  18: {
    title: "John 8:1-11:53",
  },
  19: {
    title: "John 11:54-14:31",
  },
  20: {
    title: "John 15-17",
  },
  21: {
    title: "John 18-21",
  },
  22: {
    title: "Acts 1-4",
  },
  23: {
    title: "Acts 5:1-8:3",
  },
  24: {
    title: "Acts 8:4-11:18",
  },
  25: {
    title: "Acts 11:19-13:52",
  },
  26: {
    title: "Acts 14; James 1:1-3:12",
  },
  27: {
    title: "James 3:13-5:20",
  },
  28: {
    title: "Acts 15",
  },
  29: {
    title: "Gal. 1, 2",
  },
  30: {
    title: "Gal. 3, 4",
  },
  31: {
    title: "Gal. 5, 6",
  },
};
const November = {
  1: { title: "Acts 16" },
  2: { title: "Phil. 1, 2" },
  3: { title: "Phil. 3, 4" },
  4: { title: "Acts 17:1-10" },
  5: { title: "1 Thess. 1-3" },
  6: { title: "1 Thess. 4-5" },
  7: { title: "2 Thess. 1-3" },
  8: { title: "Acts 17:11-18:11" },
  9: { title: "1 Cor. 1-4" },
  10: { title: "1 Cor. 5-7" },
  11: { title: "1 Cor. 8:1-11:1" },
  12: { title: "1 Cor. 11:2-14:40" },
  13: { title: "1 Cor. 15-16" },
  14: { title: "2 Cor. 1-4" },
  15: { title: "2 Cor. 5-7" },
  16: { title: "2 Cor. 8-10" },
  17: { title: "2 Cor. 11-13" },
  18: { title: "Acts 18:12-19:41" },
  19: { title: "Eph. 1-3" },
  20: { title: "Eph. 4-6" },
  21: { title: "Rom. 1:1-3:20" },
  22: { title: "Rom. 3:21-7:25" },
  23: { title: "Rom. 8-11" },
  24: { title: "Rom. 12, 13" },
  25: { title: "Rom. 14-16" },
  26: { title: "Acts 20:1-23:11" },
  27: { title: "Acts 23:12-26:32" },
  28: { title: "Acts 27, 28" },
  29: { title: "Col. 1:1-3:4" },
  30: { title: "Col. 3-5-4:18" },
};
const December = {
  1: { title: "Heb. 1, 2" },
  2: { title: "Heb. 3:1-4:13" },
  3: { title: "Heb. 4:14-7:28" },
  4: { title: "Heb. 8:1-10:18" },
  5: { title: "Heb. 10:19-13:25" },
  6: { title: "Titus" },
  7: { title: "Philemon" },
  8: { title: "" },
  9: { title: "" },
  10: { title: "" },
  11: { title: "" },
  12: { title: "" },
  13: { title: "" },
  14: { title: "" },
  15: { title: "" },
  16: { title: "" },
  17: { title: "" },
  18: { title: "" },
  19: { title: "" },
  20: { title: "" },
  21: { title: "" },
  22: { title: "" },
  23: { title: "" },
  24: { title: "" },
  25: { title: "" },
  26: { title: "" },
  27: { title: "" },
  28: { title: "" },
  29: { title: "" },
  30: { title: "" },
  31: { title: "" },
};

const MonthsMap = {
  0: "January",
  1: "February",
  2: "March",
  3: "April",
  4: "May",
  5: "June",
  6: "July",
  7: "August",
  8: "September",
  9: "October",
  10: "November",
  11: "December",
};

const MonthsInYear = {
  January,
  February,
  March,
  April,
  May,
  June,
  July,
  August,
  September,
  October,
  November,
  December,
};

const getTodayPlan = () => {
  const today = new Date();
  const date = today.getDate();
  const month = today.getMonth();

  return MonthsInYear[MonthsMap[month]][date]?.title || "N/A";
};

module.exports = getTodayPlan;
